- name: Comment on new issue
  # You may pin to the exact commit or the version.
  # uses: jd-solanki/gh-action-comment-on-new-issue@c443e1151cc69b146fd6918cc983ec1bd27ab254
  uses: jd-solanki/gh-action-comment-on-new-issue@v2.0.3
  with:
    # GitHub personal token
    token: # optional, default is ${{ github.token }}
    # Comment Content
    message: I'm Out of Office until Jan 2nd 2023. I'll try to check isues and help out as I can though. Tom
    # Ignore commenting when this label is found on the issue.
    ignore-label: # optional
    # Only post comment if this label is found on the issue.
    only-if-label: # optional
